
### Criar Usuário
POST http://localhost:3003/create
Content-Type: application/json

{
    "name": "Han Solo",
    "email": "hs@gmail.com",
    "password": "456"
}

### Criar Post
POST http://localhost:3003/post
Content-Type: application/json

{
    "photo": "Foto",
    "description": "Foto do Yoda",
    "type": "normal",
    "createdAt": "2023-02-03",
    "authorId": "167584",
    
}


### Buscar Post por Id
GET http://localhost:3003//posts/:id
Content-Type: application/json

{
    "id": "authorId"
}